name: Deploy nurax-stable to AWS Elastic Container Service
on:
  workflow_dispatch:
  repository_dispatch:
    types: [release]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: us-east-2
      HYRAX_TARGET: ${{ github.event.client_payload.sha }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: stable
      - uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AwsAccount }}:role/GitHubOIDCRole
          aws-region: ${{ env.AWS_REGION }}
      - run: echo "Building nurax:stable"
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        uses: docker/build-push-action@v4
        with:
          build-args: |
           "HYRAX_TARGET=${{ env.HYRAX_TARGET }}"
           "RAILS_ENV=production"
           "SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }}"
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/nurax:stable
      - name: "Force new deployment"
        run: aws ecs update-service --cluster nurax --service nurax-stable --force-new-deployment
